DEBUG = 0
FINALPACKAGE = 1

ARCHS = armv7 armv7s arm64 arm64e

include $(THEOS)/makefiles/common.mk

SUBPROJECTS += ntspeedhooks
SUBPROJECTS += ntspeedsettings

include $(THEOS_MAKE_PATH)/aggregate.mk

all::
	
